[package]
name = "cashflow"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1"
rust_decimal = { version = "1.26", features = ["serde-with-str"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"

[dev-dependencies]
rust_decimal_macros = { version = "1.26" }